version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: punto_venta_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_sistema_facturacion
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - punto_venta_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: fenc/puntodeventa-app:latest
    container_name: punto_venta_app
    ports:
      - "9898:9898"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bd_sistema_facturacion
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 9898
    networks:
      - punto_venta_network

networks:
  punto_venta_network:
    driver: bridge

volumes:
  mysql_data: 